force-app/main/default/objects/Opportunity/fields/Profile__c.field-meta.xml
<CustomField>
    <fullName>Profile__c</fullName>
    <label>Profile</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Low</fullName>
            </value>
            <value>
                <fullName>Medium</fullName>
            </value>
            <value>
                <fullName>High</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/VIP_Profile__c.field-meta.xml
<CustomField>
    <fullName>VIP_Profile__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Opportunities with Amount &gt; 50000</description>
    <label>VIP Profile</label>
    <type>Checkbox</type>
</CustomField>

Demanda159/classes/CheckVIP.cls
public class CheckVIP {

public static void isVIP(List<Id> listaId){
    List<Opportunity> attOpp = [SELECT Id, Profile__c, VIP_Profile__c  FROM Opportunity WHERE Id IN:listaId];
    List<Opportunity> attDML = new List<Opportunity>();
        
        for (Opportunity opp : attOpp) {
        if(opp.Profile__c == 'High'){
            opp.VIP_Profile__c=true;
        } else{
            opp.VIP_Profile__c=false;
        }
        attDML.add(opp);
    } update attDML;
}
}